CREATE TABLE sms_message (
    id VARCHAR(255) PRIMARY KEY,
    message TEXT NOT NULL,
    is_allowed BOOLEAN DEFAULT FALSE,
    is_safe BOOLEAN DEFAULT TRUE,

    received_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);